/**
 * Shape of `public/library/scratch-catalog.json`, generated by
 * `scripts/build-scratch-catalog.ts` from Scratch's own library catalogs.
 *
 * Deliberately carries no width/height: Scratch's catalogs don't either, and a
 * cached dimension can disagree with the file it describes. Dimensions are
 * measured in the browser at fetch time. See docs/sprite_libraries.md.
 *
 * This module imports nothing so every consumer can read it — the same
 * constraint projectSchema.ts is under.
 */

/** A costume or backdrop. `res` is Scratch's bitmapResolution: 2 means retina. */
export interface CatalogImage {
  name: string
  tags: string[]
  md5ext: string
  res: number
}

/** A sound. `seconds` is precomputed from sampleCount/rate. */
export interface CatalogSound {
  name: string
  tags: string[]
  md5ext: string
  seconds: number
}

/** A sprite: a costume set plus the sounds Scratch ships with it. */
export interface CatalogSprite {
  name: string
  tags: string[]
  costumes: { name: string; md5ext: string; res: number }[]
  sounds: { name: string; md5ext: string }[]
}

export interface ScratchCatalog {
  /** `scratch-gui@<sha>` — the pinned commit the catalog was generated from. */
  source: string
  license: string
  sprites: CatalogSprite[]
  costumes: CatalogImage[]
  backdrops: CatalogImage[]
  sounds: CatalogSound[]
}

export const CATALOG_URL = '/library/scratch-catalog.json'
